# Generated by Django 2.0.6 on 2018-06-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.SmallIntegerField(db_column='categoryid', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='categoryname', max_length=15)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('picture', models.BinaryField(blank=True, db_column='picture', null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.SmallIntegerField(db_column='productid', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='productname', max_length=40)),
                ('quantity_per_unit', models.CharField(blank=True, db_column='quantityperunit', max_length=20, null=True)),
                ('unit_price', models.FloatField(blank=True, db_column='unitprice', null=True)),
                ('units_in_stock', models.SmallIntegerField(blank=True, db_column='unitsinstock', null=True)),
                ('units_on_order', models.SmallIntegerField(blank=True, db_column='unitsonorder', null=True)),
                ('reorder_level', models.SmallIntegerField(blank=True, db_column='reorderlevel', null=True)),
                ('discontinued', models.IntegerField(db_column='discontinued')),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.SmallIntegerField(db_column='supplierid', primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_column='companyname', max_length=40)),
                ('contact_name', models.CharField(blank=True, db_column='contactname', max_length=30, null=True)),
                ('contact_title', models.CharField(blank=True, db_column='contacttitle', max_length=30, null=True)),
                ('address', models.CharField(blank=True, db_column='address', max_length=60, null=True)),
                ('city', models.CharField(blank=True, db_column='city', max_length=15, null=True)),
                ('region', models.CharField(blank=True, db_column='region', max_length=15, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='postalcode', max_length=10, null=True)),
                ('country', models.CharField(blank=True, db_column='country', max_length=15, null=True)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=24, null=True)),
                ('fax', models.CharField(blank=True, db_column='fax', max_length=24, null=True)),
                ('homepage', models.TextField(blank=True, db_column='homepage', null=True)),
            ],
            options={
                'db_table': 'suppliers',
                'managed': False,
            },
        ),
    ]
